This is makeindex, version 2.15 [TeX Live 2016/W32TeX] (kpathsea + Thai support).
Scanning style file ./tesi.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file .\tesi.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (11 comparisons).
Generating output file .\tesi.acr....done (17 lines written, 0 warnings).
Output written in .\tesi.acr.
Transcript written in .\tesi.alg.
